[FEAT] 버스 통계 서비스 구현
Kernel360/E2E2-TALKKA pull request #114
Opened 2024-08-23 14:49 UTC by Gyaak

- 버스 통계 서비스 구현
  - 버스 위치정보 가공 로직 구현

close #113

2024-08-23 16:16 UTC, JuneParkCode commented on server/build.gradle
Retry 라는 것도 있었네요. 관련해서 정리 한번 남겨주시면 좋을 것 같습니다.

2024-08-23 16:16 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/BusLocationService.java
> +import jakarta.transaction.Transactional;
Jakarta로 변경하신 이유가 궁금합니다

2024-08-23 16:16 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/enums/EndBus.java
> +	RUNNING("0"), END("1"), END_BUS_CODE2("2"), LENT_BUS_END("4");
눈물나는데 답이 따로 없네요. 나중에 찾아보고 변경해봅시다

2024-08-23 16:16 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dao/BusStatEntity.java
> +	public int hashCode() {
Hash/equals는 id 로 변경필요

2024-08-23 16:16 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/BusLocationCollectService.java
> +	void collectLocationsByRouteId(String apiRouteId);
의도는 이해됩니다만, 조금 수정이 필요해보입니다.

지금은 딱히 좋은 방법이 생각나지 않아, 추후에 댓글 더 남겨보갰습니다

2024-08-23 16:16 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/LocationCollectingScheduler.java
> -			busLocationCollectService.collectLocations();
위에 수정필요하다고 생각한 부분이 이쪽하고 연결되네요.

해당 로직 부분을 parallelCollectService 로 만들고 인터페이스 보존 후 구현체를 바꾸는걸로 해결하는건 어떨까요..?

2024-08-23 16:35 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dao/BusStatEntity.java
> +	public int hashCode() {
데이터 가공 할 때, 중복체크용으로 해시코드를 사용하기 위해 일부러 id와 createdAt을 제외하고 해시코드를 오버라이드 했는데,
다시 생각해보니 equals&hashcode는 entity id로 비교하고,
데이터 가공할때 사용할 중복체크 메소드를 따로 만드는 것이 좋을거같네요.. 수정하겠습니다.

2024-08-23 16:35 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/service/BusLocationService.java
> +import jakarta.transaction.Transactional;
두 어노테이션 차이에 대해 정확히 이해하고 있지 않아 실수한것 같습니다.
`import org.springframework.transaction.annotation.Transactional` 로 변경하고 차이에 대해서는 기술부채에 정리해두도록 하겠습니다.

2024-08-23 16:35 UTC, Gyaak commented on server/build.gradle
스프링 배치와 함께 기술부채쪽에 정리해두도록 하겠습니다

2024-08-23 16:37 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/LocationCollectingScheduler.java
> -			busLocationCollectService.collectLocations();
Pararell 사용하는 것 때문에, 이와 관련된 의존성 중 상태를 갖는 getKey 부분에 대해 thread safe 하게 코드를 작성해두면 좋을 것 같습니다. 실제로 문제가 발생할 지에 대해서는 모르겠어서 테스트 코드를 통해 한번 실험해보는 것도 좋을 것 같아요.

2024-08-24 02:15 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
>  			URI uri = this.getOpenApiUri(path, params);
아래 로직으로 변경됨에 따라 삭제 필요

2024-08-24 02:24 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/bus/dao/BusLocationRepository.java
> +
해당 쿼리에서 l 별칭이 필요 없어 보입니다!

2024-08-24 02:26 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/bus/enums/EndBus.java
> +	RUNNING("0"), END("1"), END_BUS_CODE2("2"), LENT_BUS_END("4");
월요일에 전화한번 해보죠...
대체 이게 뭐냐고...

2024-08-24 02:32 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/bus/service/BusStatService.java
> +import jakarta.transaction.Transactional;
해당 어노테이션도 jakarta로 되어있어서 수정 필요

2024-08-24 02:41 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dao/BusLocationRepository.java
> +
수정하겠습니다.

2024-08-24 02:41 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/service/BusStatService.java
> +import jakarta.transaction.Transactional;
수정하겠습니다.

2024-08-24 05:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
> +	private <T> ResponseEntity<T> apiCallWithRetry(String path, MultiValueMap<String, String> params,
이 친구 Abstract class도 빼도 좋을 것 같아요.

2024-08-24 05:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
> +		final int RETRY_INTERVAL = 200;
MAX_ATTEMPS 3회정도면 충분해보입니다! 다른 파트에서 주입할 수 있으면 더 좋을듯...?

2024-08-24 05:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/BusStatService.java
> +	// }
보존 안해도되면 삭제해도 될 듯 싶습니다.

2024-08-24 10:04 UTC, Gyaak commented on server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
> +		final int RETRY_INTERVAL = 200;
이건 이번주말에 분리하도록 리팩토링할 예정이라 그때 수정하도록 하겠습니다.

2024-08-24 10:05 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/service/BusStatService.java
> +	// }
혹시 몰라서 냅두겠습니다.

2024-08-24 10:06 UTC, Gyaak commented on server/src/main/java/com/talkka/server/api/datagg/service/SimpleBusApiService.java
> +	private <T> ResponseEntity<T> apiCallWithRetry(String path, MultiValueMap<String, String> params,
리팩토링 진행 하면서 별도 클래스로 분리해 빈으로 등록하는것 고려중입니다.

2024-08-24 15:09 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dto/BusStatRespDto.java
> +	Integer minute,
이 부분들은 나중에 Refactoring 할 때 조금 더 엄밀하게 VO 로 체크되면 좋을 것 같아요.

2024-08-24 15:13 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dto/BusStatRespDto.java
> +	Integer minute,
너무 다 던지는 느낌이 있어서 (일단은 이것도 쓸수도...?) 나중에 필요한 부분만 빼다가 보여주는게 필요합니다

예를 들어,
7800 - 성균관대 - 현재시각(07:00) 의 "들어오는 좌석수"를 요청하면 
06:30 ~ 07:30 의 "들어오는 좌석수" - "시간" 의 배열 반환이면 충분합니다.

이런 식으로 해당 정류장에서 몇 명이 타는지... 이런 데이터들을 표현해야합니다.

2024-08-24 15:29 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dto/BusStatRespDto.java
> +	Integer minute,
현재 시간 기준으로 조회하는 메소드 하나 추가하겠습니다!

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/controller/BusLocationProcessController.java
> +	@PostMapping("/process/all")
admin 권한 필요 (bus쪽은 공개되어있습니다.)

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/controller/BusViewController.java
> +	@GetMapping("/now")
View 라는 이름이 모호하다고 생각합니다.

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/controller/BusViewController.java
> +	) {
해당 controller 임시로 둔 것으로 이해해도 될까요? (추후에 제가 수정하게 되는 컨트롤러)

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dao/BusLocationEntity.java
> +	private Integer remainSeatCount;
변경되면서 다른 쪽에서 터질 수 있을 것 같은데 염두에 두겠습니다!

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dao/BusRemainSeatEntity.java
> +	private BusPlateStatisticEntity routeInfo;
실제로 많이 가져올 일이 없어 LAZY 뒀다고 생각해도 될까요

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dao/BusRemainSeatEntity.java
> +	}
Entity 말고 다른 TimeUtil 같은걸로 빼면 좋겠습니다.

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dto/BusRemainSeatDto.java
> +	}
따로 이렇게 두신 이유가 궁금합니다..!

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dto/BusRemainSeatDto.java
> +			standardTime = seats.get(seats.size() >> 1).getCreatedAt();
요기는 어떤 의미를 가지고 있는지 궁금합니다.

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/BusLocationProcessor.java
> +		}
나중에 리팩토링 꼭 필요합니다. depth가 너무 깊네요.

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/service/BusLocationProcessor.java
> +		assert locations.peek() != null;
이 부분 확실한 부분인가요?

2024-08-28 05:29 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/common/util/TimeSlotTypeConverter.java
> +}
사용하는 Entity에서 왜 이렇게 저장하는지를 명시해주시면 좋을 것 같습니다.

2024-08-28 05:39 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/controller/BusLocationProcessController.java
> +	@PostMapping("/process/all")
관리자페이지 완성 후 adminController로 옮길 예정입니다.

2024-08-28 05:40 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/controller/BusViewController.java
> +	) {
네 맞습니다. 프론트에 맞춰서 수정하시면 됩니다.

2024-08-28 05:42 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dao/BusLocationEntity.java
> +	private Integer remainSeatCount;
추후 리팩토링 예정

2024-08-28 05:46 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dao/BusRemainSeatEntity.java
> +	private BusPlateStatisticEntity routeInfo;
네 맞습니다.

2024-08-28 05:54 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dto/BusRemainSeatDto.java
> +	}
Serializable은 삭제했습니다.
arrivedTime과 remainSeat을 한쌍으로 묶어 json으로 내보내기 위해 inner class를 추가했습니다.

2024-08-28 05:55 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/service/BusLocationProcessor.java
> +		assert locations.peek() != null;
네 process 호출 전 locations가 empty인지 확인합니다.

2024-08-28 05:58 UTC, Gyaak commented on server/src/main/java/com/talkka/server/bus/dto/BusRemainSeatDto.java
> +			standardTime = seats.get(seats.size() >> 1).getCreatedAt();
요청한 정거장 기준으로 앞뒤로 빈좌석과 도착시간 등을 조회하게 되는데,
이때 기준이 된 정거장에 도착한 시간을 얻는 코드입니다.
총 정거장의 개수가 항상 홀수이고, 기준이 된 정거장이 중앙에 위치하기 때문에 size/2 중앙 정거장의 인덱스를 가져올 수 있습니다.

2024-08-28 06:07 UTC, Gyaak commented on server/src/main/java/com/talkka/server/common/util/TimeSlotTypeConverter.java
> +}
TimeSlot 별로 집계 할 때 사용했었는데 집계 방식이 변경되어 사용하지 않게 되었습니다.
Converter삭제 및 TimeSlot enum 롤백 했습니다.

2024-08-28 06:15 UTC, JuneParkCode requested changes

2024-08-28 06:15 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dto/BusRemainSeatDto.java
> +			standardTime = seats.get(seats.size() >> 1).getCreatedAt();
1. `seats` -> 변수명으로부터 list 임이 잘 와닿지 않아, 37번 라인의 의미 해석이 어렵습니다.
2. 비슷한 문제로 `seats.size()` 부분이 해당 배열의 크기를 구한다는 의미임을 처음에 인지하지 못하는 문제가 있었습니다.
3. shift 연산자로 표현하는 것이 가독성이 굉장히 좋지 않았습니다.
4. 결과적으로 `seats.get(seats.size() >> 1)` 부분은 `배열의 중간 요소를 구한다` 라는 의미의 method로 분리하는 것이 조금 더 잘 읽힐 것 같습니다.
5. `seats.size() >> 1` 또한 왜 해당 행위를 해야하는 지에 대해서 의미적으로 잘 전달되지 않아, private method 화 하는 것이 어떨까 제안드립니다.

2024-08-28 06:16 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/dto/BusRemainSeatDto.java
> +	}
이후에 open api docs로 잘 빠지는지 확인 필요...

2024-08-28 06:17 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/bus/controller/BusViewController.java
> +	@GetMapping("/now")
해당 부분은 다른 controller 를 통하게 될 것임. 테스트용 임시 컨트롤러로 유지하고 이후 작업에서 변경하도록 할 것임.

2024-08-28 06:33 UTC, JuneParkCode approved these changes
LGTM

2024-08-28 06:41 UTC, ss0ngcode approved these changes

2024-08-28 06:44 UTC, merged