[FEAT] 관리자 페이지 구현
Kernel360/E2E2-TALKKA pull request #119
Opened 2024-08-25 15:51 UTC by Gyaak

## 관리자 페이지 구현
- 사용자 관리
- 정거장 노선 별 북마크 개수 통계
- 정거장 노선 별 리뷰 개수 통계
- 수집 노선 관리(아직 api call에서 끌어다 쓰지는 않음 - CRUD)

close #115

2024-08-26 01:55 UTC, JuneParkCode requested changes

2024-08-26 01:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/admin/controller/AdminController.java
> +	@Secured(("ADMIN"))
괄호 두 개로 되어있음 수정 필요

2024-08-26 01:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/admin/dao/CollectBusRouteEntity.java
> +	private BusRouteEntity route;
routeId만 명시해도 괜찮을 것 같다는 생각이 듭니다. (실제 조회가 일어나지 않는 것 같아요.)

2024-08-26 01:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/admin/dto/BookmarkStatRespDto.java
> +	BusRouteStationRespDto busRouteStation,
이 친구는 왜 붙는지 궁금합니다.

2024-08-26 01:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/admin/dto/BusReviewStatRespDto.java
> +	BusRouteStationRespDto busRouteStation,
여기도 마찬가지 입니다.

2024-08-26 01:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/admin/service/CollectBusRouteService.java
> +		if (collectBusRouteRepository.findByRouteId(dto.routeId()).isPresent()) {
existsById로 바꾸는게 좋을 것 같아요.

2024-08-26 01:55 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/admin/service/CollectBusRouteService.java
> +		if (collectBusRouteRepository.findById(collectRouteId).isEmpty()) {
여기도 마찬가지로 existsById..

2024-08-26 01:56 UTC, JuneParkCode commented on server/src/main/resources/templates/dev/dev-index.html
빈 파일입니다.

2024-08-26 01:57 UTC, JuneParkCode commented
schema 파일 업데이트 필요합니다.

2024-08-26 01:58 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/admin/controller/AdminController.java
> +	@Secured("ADMIN")
해당 어노테이션 사용하지 않고 SecurityConfig에 있는 접근 제한으로 해결해도 될 듯 합니다!

2024-08-28 13:30 UTC, Gyaak commented on server/src/main/java/com/talkka/server/admin/dao/CollectBusRouteEntity.java
> +	private BusRouteEntity route;
관리자 페이지에서 해당 노선 정보를 보여주기 위해서 넣었습니다.

2024-08-28 23:58 UTC, JuneParkCode commented
al.DefaultToolchainJavaCompiler] Compiling with toolchain '/opt/hostedtoolcache/Java_Corretto_jdk/17.0.12-7.1/x64'.
2024-08-28T23:49:16.7782047Z 2024-08-28T23:49:14.276+0000 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 17 -target 17 -d /home/runner/work/E2E2-TALKKA/E2E2-TALKKA/server/build/classes/java/main -encoding UTF-8 -h /home/runner/work/E2E2-TALKKA/E2E2-TALKKA/server/build/generated/sources/headers/java/main -g -sourcepath "" -processorpath /home/runner/.gradle/caches/modules-2/files-2.1/org.projectlombok/lombok/1.18.34/ec547ef414ab1d2c040118fb9c1c265ada63af14/lombok-1.18.34.jar -s /home/runner/work/E2E2-TALKKA/E2E2-TALKKA/server/build/generated/sources/annotationProcessor/java/main -XDuseUnsharedTable=true -classpath /home/runner/.gradle/caches/modules-2/files-2.1/org.projectlombok/lombok/1.18.34/ec547ef414ab1d2c040118fb9c1c265ada63af14/lombok-1.18.34.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-validation/3.3.2/81ee06b318ed35c2a3f4882a0f7b9946a39e1b39/spring-boot-starter-validation-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-data-jpa/3.3.2/2731d74dfc18fb905c29930cf55493980c2cee5a/spring-boot-starter-data-jpa-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-security/3.3.2/13a1d62a33323306fcd4c4cbb6a98322ce633ac0/spring-boot-starter-security-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-web/3.3.2/720418538668a8742d0ae24097811d5250cf5c32/spring-boot-starter-web-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-thymeleaf/3.3.2/cdcc62e2bb84c080a474281cf09c28cdfd423955/spring-boot-starter-thymeleaf-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-oauth2-client/3.3.2/7d11c36d5c85f02597cff89c7a045ebfe213b8f1/spring-boot-starter-oauth2-client-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-json/3.3.2/d8b8b73e7820092b4e41d730eeb968add7957c45/spring-boot-starter-json-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.17.2/efd3dd0e1d0db8bc72abbe71c15e697bb83b4b45/jackson-datatype-jdk8-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springdoc/springdoc-openapi-starter-webmvc-ui/2.0.2/264da79c9d4a53feab8c5c6d0e0cb143bd099d4/springdoc-openapi-starter-webmvc-ui-2.0.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springdoc/springdoc-openapi-starter-webmvc-api/2.0.2/479a5cd03969a22d9f8b819ef92c54433e08034a/springdoc-openapi-starter-webmvc-api-2.0.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springdoc/springdoc-openapi-starter-common/2.0.2/5f668e69d620c56db3ba9689d48d6b64e42235b9/springdoc-openapi-starter-common-2.0.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/io.swagger.core.v3/swagger-core-jakarta/2.2.7/9111d85fc116ad6ec9d5f6f54edf81c2740e52/swagger-core-jakarta-2.2.7.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.17.2/267b85e9ba2892a37be6d80aa9ca1438a0d8c210/jackson-datatype-jsr310-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.17.2/d27b9f95ccce98984c1ba58d61c5a9c072b1ad95/jackson-module-parameter-names-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.17.2/78d2c73dbec62044d7cf3b544b2e0d24a1a093b0/jackson-dataformat-yaml-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.17.2/e6deb029e5901e027c129341fac39e515066b68c/jackson-databind-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.17.2/969a35cb35c86512acbadcdbbbfb044c877db814/jackson-core-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/io.swagger.core.v3/swagger-models-jakarta/2.2.7/b26a24f51b009fe77a0b4b4f67738a60aaff1aa2/swagger-models-jakarta-2.2.7.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.17.2/147b7b9412ffff24339f8aba080b292448e08698/jackson-annotations-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.17.2/ad58f5bd089e743ac6e5999b2d1e3cf8515cea9a/jackson-dataformat-xml-2.17.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.retry/spring-retry/2.0.7/f7b22a785a35cf0927277dceb5db1c6de1d6259b/spring-retry-2.0.7.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-aop/3.3.2/26d996e253768d3121bb3ffbef28cefc07fdbddb/spring-boot-starter-aop-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-jdbc/3.3.2/544775d745288972598ab2e872e5a4816b6d9b39/spring-boot-starter-jdbc-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter/3.3.2/f9377a223dab5c4afe7aead05bf6ac567cf565ab/spring-boot-starter-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-tomcat/3.3.2/37ccb53cd5207fffd7a6fc1b591687f8cb1350df/spring-boot-starter-tomcat-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/10.1.26/5a5cbcb3e51fcd557b164736e9920a3dd2ac1e33/tomcat-embed-el-10.1.26.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.hibernate.validator/hibernate-validator/8.0.1.Final/e49e116b3d3928060599b176b3538bb848718e95/hibernate-validator-8.0.1.Final.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.hibernate.orm/hibernate-core/6.5.2.Final/e9e0cc47f6cd2b2553968aee66bd9e55e7485221/hibernate-core-6.5.2.Final.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.data/spring-data-jpa/3.3.2/cfa9cd077f3f15d0657bbb6d7c8e1c7c7da7e6e2/spring-data-jpa-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aspects/6.1.11/141d92094a460f338aa0999023ca7a25861d49a1/spring-aspects-6.1.11.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-config/6.3.1/e4f6c1cf4f8969c9e5ed26121f0fbd7ee35a7ca4/spring-security-config-6.3.1.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-oauth2-client/6.3.1/395023fa3fd09e51d39f36bcb60050f22ae4757d/spring-security-oauth2-client-6.3.1.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-web/6.3.1/aff43933f28c808252b2d31f768b92fa61b634f6/spring-security-web-6.3.1.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/6.1.11/9ec4c2a5e28bf7b2d60e254e976940b12c8ba32a/spring-webmvc-6.1.11.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-oauth2-jose/6.3.1/442a8af56b7f108473e146af0b21bd3b1538e194/spring-security-oauth2-jose-6.3.1.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-oauth2-core/6.3.1/2f68a3b5a10022599b72430eb89bde5e6630975c/spring-security-oauth2-core-6.3.1.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-core/6.3.1/598c2461a17c29705ca7fd8c02efd23a1f650ccd/spring-security-core-6.3.1.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/3.3.2/6a9ab910b00f0b504a5903e3680ac10018da6247/spring-boot-autoconfigure-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/3.3.2/72a257d5518b2b8b9949a26543cdb3a4e67de5f8/spring-boot-3.3.2.jar:/home/runner/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/6.1.11/8fc69f776333713aa26be8821af [...]

2024-08-28 23:59 UTC, JuneParkCode commented
PublicApiKeyProvider 를 현재 찾지 못하여 빌드 오류 발생합니다 확인 부탁드립니다.

+ develop branch 동기화 해두었으니 pull 확인 부탁드립니다

2024-08-29 02:04 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/admin/service/AdminService.java
> +	}
해당 메서드가 아래 메서드와 중복되는 부분이 많아보이는데 제네릭 이용해서 통합하는건 어떨까요?

2024-08-29 02:07 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/bus/service/LocationCollectingScheduler.java
해당 클래스가 변경되서 TEST 코드에서 에러가 발생하는 것으로 보입니다.
수정 부탁드려요!

2024-08-29 02:24 UTC, Gyaak commented on server/src/main/java/com/talkka/server/admin/dto/BusReviewStatRespDto.java
> +	BusRouteStationRespDto busRouteStation,
관리자 페이지에서 노선-정거장 별로 그룹핑해서 보여주는데, 노선-정거장 정보 + 리뷰 수 를 같이 보여주기 위해 넣었습니다.

2024-08-29 02:25 UTC, Gyaak commented on server/src/main/java/com/talkka/server/admin/dto/BookmarkStatRespDto.java
> +	BusRouteStationRespDto busRouteStation,
관리자 페이지에서 노선-정거장 별로 그룹핑해서 보여주는데, 노선-정거장 정보 + 북마크 수를 같이 보여주기 위해 넣었습니다.

2024-08-29 04:54 UTC, JuneParkCode approved these changes
LGTM, 테스트에서 빈 주입 안되는 문제는 E2E 이후 분석해서 수정이 필요함

2024-08-29 05:02 UTC, merged