[FEAT] EC2 환경 구성 및 CI/CD 구현
Kernel360/E2E2-TALKKA pull request #125
Opened 2024-08-28 03:02 UTC by ss0ngcode

## 작업 내용
- server를 컨테이너로 올리기 위해 docker compose에 작성
- nginx 및 ssl인증(certbot)을 위해 docker compose에 작성
- ssl 인증을 위한 init-letsencrypt.sh 작성
- Github Action을 통해 CI / CD를 위한 gradle-build.yml 작성

## 전달 사항
- CI / CD를 위해 main 브랜치 push 규칙
  - version: 뒤에 붙은 키워드를 version tag로 사용함
    - 해당 commit message에서 1.0을 추출하여 docker hub push시에 tag로 사용
  - commit message를 이와 같이 해야함
    - version: 1.0

2024-08-28 05:30 UTC, JuneParkCode requested changes

2024-08-28 05:30 UTC, JuneParkCode commented on .github/workflows/gradle-build.yml
Fork 된 곳에서 테스트 필요합니다.

2024-08-28 06:39 UTC, Gyaak approved these changes
배포 고생하셨습니다.

2024-08-28 23:46 UTC, JuneParkCode commented
https://github.com/ss0ngcode/E2E2-TALKKA/actions/runs/10597248871

배포 확인 / API URL 공유 부탁드립니다

2024-08-29 01:55 UTC, JuneParkCode approved these changes

2024-08-29 01:56 UTC, merged

2024-08-29 01:58 UTC, ss0ngcode commented
> https://github.com/ss0ngcode/E2E2-TALKKA/actions/runs/10597248871
> 
> 배포 확인 / API URL 공유 부탁드립니다


nginx.conf 파일에서 확인 가능합니다!

DNS 주소는 
talkka-bus.duckdns.org 이며
일단 8080으로 연결되는건 `location /`로 설정해두어서 기존 로컬에서 테스트 하듯 talkka-bus.duckdns.org/{API_PATH}로 적으시면 됩니다!