[eat] #8 버스 관련 리뷰 CRUD 추가
Kernel360/E2E2-TALKKA pull request #33
Opened 2024-08-02 10:55 UTC by ss0ngcode

- 버스 리뷰 조회 (버스, 정류장, 시간대 옵션)
- 버스 리뷰 생성
- 버스 리뷰 수정 (리뷰, 시간대, 별점 옵션)
- 버스 리뷰 삭제

2024-08-02 11:26 UTC, JuneParkCode requested changes
고생 많이하셨습니다. 몇몇 부분 고칠 점이 보여서 Request Changes 남깁니다~

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
> +	private Optional<String> content;
Field에서 Optional 쓰면 직렬화에 문제가 있는 것으로 알고 있습니다.
Optional은 Return value 로 쓰도록 고안되었다고 합니다. (저도 이 기회에 배웠네요)
잘 생각해보면 method 에서 해당 값이 존재할 수도, 아닐 수도 있는 경우를 효과적으로 나타내는 방법이라고 볼 수 있습니다.

해당 내용 확인해보시고 수정해주세요~

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		.build();
조금은 생각해볼만한 부분인 것 같아요. final 객체라고 해도 Entity 자체가 setter 가 지금 있는 상태이고, 테스트 중간에 변경이 일어난다면 다른 테스트에 영향을 미칠 수 있는 요소가 될 수 있을 것으로 보입니다.

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +			given(busReviewRepository.save(any(BusReviewEntity.class))).willReturn(busReviewEntity);
맨 아래 `any(.class)` 부분처럼 `given` 값을 주는 것이 더 좋을 것 같아요.
아까 해덕님이 값이 변화하는 경우에 대해서 이야기를 해주셨는데, 이 부분도 연관되지 않을까? 생각이 듭니다. (저도 테스트를 잘 아는 편은 아니라서 확신은 안드네요.)

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		void 제한된_요청에_따라_버스리뷰를_생성한다() {
rating 이 엉뚱한 값이 들어오는 경우에 대해서도 검증이 있으면 좋겠습니다.

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
> +		List<BusReviewEntity> list = optionalList.orElseGet(ArrayList::new);
reference 를 바꾸지 않는 객체에 대해서는 final을 붙이는게 더 명확하게 의미가 전달되리라 생각합니다.

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
> +	}
reviewId 가 존재하지 않는 경우에 대한 예외처리가 없습니다.

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
> +	private Integer rating;
이건 제 코드에서도 좀 생각해볼 부분인 것 같은데요.
Long, Integer 보다 long, int 로 표현해도 충분한 값이 아닌가 싶습니다. (각 장단에 대해서 생각좀 해봐야할듯)

2024-08-02 11:26 UTC, JuneParkCode commented on server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
> +	}
이 부분 저희가 제대로 논의를 안하고 넘어갔네요.
create 결과로 201만 반환할 것인지, 결과값을 같이 보내줄 것인지 같이 이야기해봐야할 것 같습니다.

2024-08-02 11:41 UTC, Gyaak commented on server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
> +		@RequestParam Integer timeSlot
TimeSlot의 타입에 대해 고민해보면 좋을것 같습니다.
0~48값을 가지고 각 값은 하루를 48등분 한 시간구간을 가진다고 정의했지만,
값의 의미가 직관적이지 않아서 Enum타입으로 변경해 보는것도 좋을것같습니다.

2024-08-02 11:41 UTC, Gyaak commented on server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
> +	public Optional<List<BusReviewEntity>> findAllByUserIdAndRouteIdAndStationIdAndTimeSlot(
리스트는 빈 리스트를 반환하면 되니 Optional로 감싸지 않는것도 고려해볼 수 있을거같아요

2024-08-02 11:41 UTC, Gyaak commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
> +			.orElse(null));
null값이 허용되는 필드라면 Optional없이 그냥 받아도 될것같습니다.

2024-08-04 13:12 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
> +	private Optional<String> content;
Optional을 찾아보니 Serializable 인터페이스를 구현하지 않아 직렬화 문제가 있는게 맞더라구요.
해당 내용 반영하여 Optional은 필드에서 모두 제거했습니다!

2024-08-04 13:13 UTC, ss0ngcode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		.build();
final에 대한 내용은 회의때 논의한 내용으로 처리하였습니다!

2024-08-04 13:13 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
> +		List<BusReviewEntity> list = optionalList.orElseGet(ArrayList::new);
위와 동일하게 회의때 논의된 내용으로 진행하도록 하겠습니다!

2024-08-04 13:14 UTC, JuneParkCode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		.build();
여기서는 조금 다른 이슈입니다. 해당 객체가 test 에서 전반적으로 사용되어 발생하는 문제입니다.

2024-08-04 13:20 UTC, ss0ngcode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		.build();
아.. 어떤 말씀이신지 이해했습니다!
해당 내용에 대해서는 좀 더 고민해보도록 하겠습니다.

2024-08-04 13:35 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
> +	private Integer rating;
wrapper에 대해서는 월요일에 만나 논의를 해보면 좋을 것 같습니다!

dto와 entity 모두...

2024-08-04 14:37 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
> +	}
아.. 아이디 값 존재 유무 확인에 대한 예외처리 추가했습니다!

2024-08-04 14:40 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
> +			.orElse(null));
생각해보니 그렇네요...
어차피 null이 허용되니 저건 있으나 마나한...

추가로 해당 로직은 dto에서 setter를 빼고 update에 대한 메서드를 하나 추가해서 사용하는 걸로 변경되었습니다!
자세한 이야기는 내일 말씀드리겠습니다!

2024-08-05 02:37 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/dto/BusReviewRespDto.java
> +	private Integer rating;
dto, Entity 모두 wrapper 사용하는 것으로 결정되었습니다!

2024-08-05 02:38 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
> +		@RequestParam Integer timeSlot
enum타입으로 생성하여 사용하는 것으로 결정되었습니다!

2024-08-05 02:38 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/dao/BusReviewRepository.java
> +	public Optional<List<BusReviewEntity>> findAllByUserIdAndRouteIdAndStationIdAndTimeSlot(
Optional을 제외하고 JPQL로 쿼리 구성하였습니다!

2024-08-05 03:18 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/controller/BusReviewController.java
> +	}
회의를 통해 create 결과로 객체 전부를 넘겨주기로 결정되었고
상태는 OK를 넘겨주기로 통일되었습니다!

2024-08-05 03:44 UTC, ss0ngcode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		void 제한된_요청에_따라_버스리뷰를_생성한다() {
requestDto에서 validation 처리하는 것으로 수정했습니다!

2024-08-05 03:45 UTC, ss0ngcode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +			given(busReviewRepository.save(any(BusReviewEntity.class))).willReturn(busReviewEntity);
해당 내용 반영 하였습니다!

2024-08-05 03:45 UTC, ss0ngcode commented on server/src/test/java/com/talkka/server/review/service/BusReviewServiceTest.java
> +		.build();
해당 내용에 대해 메서드로 따로 빼서 처리하였습니다!

2024-08-05 03:51 UTC, Gyaak approved these changes

2024-08-05 03:51 UTC, Gyaak commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
>  			.collect(Collectors.toList());
.toList() 로 더 간단하게 표현 가능

2024-08-05 03:51 UTC, Gyaak commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
>  		busReviewRepository.deleteById(busReviewId);
작성자 또는 관리자만 삭제하도록 체크하는 로직 필요

2024-08-05 03:57 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
>  			.collect(Collectors.toList());
해당 내용 반영

2024-08-05 03:57 UTC, ss0ngcode commented on server/src/main/java/com/talkka/server/review/service/BusReviewService.java
>  		busReviewRepository.deleteById(busReviewId);
회원 기능 완료 이후 리팩토링 예정

2024-08-05 05:03 UTC, merged